// This is used as the "entry" for the service worker, i.e.
// additional code that is not generated by the offline-plugin

import toolbox from 'sw-toolbox';

toolbox.precache([
  '/web/getting-started',
  '/web/timelines/home'
]);

const webUrls = [
  '/web/getting-started',
  '/web/timelines/home',
];

const signOutRegex = /\/auth\/sign_out$/;

toolbox.router.get(webUrls, toolbox.cacheFirst);
toolbox.router.get('/emoji/*', toolbox.cacheFirst);

self.addEventListener('fetch', event => {
  const { url, method } = event.request;
  if (method === 'POST' && signOutRegex.test(url)) {
    // on sign out, clear any /web paths because we need to update the
    // csrf-token (whereas everything else is static, no harm in caching)
    return Promise.all(webUrls.map(webUrl => {
      const fullUrl = new URL(url.toString().replace(signOutRegex, webUrl));
      return toolbox.uncache(fullUrl);
    })).then(() => {
      return fetch(event.request);
    });
  } else {
    return fetch(event.request);
  }
})
