// This is custom functionality added to the ServiceWorker in addition
// to the code generated by offline-plugin

// https://mastodon.social/auth/sign_out

self.addEventListener('fetch', event => {
  const requestUrl = event.request.url;
  const requestMethod = event.request.method;
  if (/\/auth\/sign_out$/.test(requestUrl) && requestMethod === 'POST') {
    console.log('signout!!');
  }
});
